Trying to find Ninja on the new image

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -86,6 +86,7 @@ jobs:
 
     - name: Build and Install Release
       run: |
+        which ninja || (echo "ninja-build not found, installing..." && sudo apt-get update && sudo apt-get install -y ninja-build)
         . .venv/bin/activate && make release all install
 
     - name: Run Tests
@@ -129,6 +130,7 @@ jobs:
 
     - name: Build and Install Debug
       run: |
+        which ninja || (echo "ninja-build not found, installing..." && sudo apt-get update && sudo apt-get install -y ninja-build)
         . .venv/bin/activate && make debug all install
 
     - name: Run Coverage
